# -*- coding: utf-8 -*-
"""ResultReproduceLAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-Y-if3NAXz3vxZ-UYklEhzRalDE3POJ
"""

print("Fatima");

#variables
x = 4
y = 5
print(x + y)

x = str('Fatima')
y = int(6)
z = float(6)
print(x)
print(y)
print(z)

a = 5
print(type(a))

a = 6
A = "Fatima"
print(a)
print(A)

_a = 4
a = 6
b1 = 34

a, b, c = "Maths", "Chemistry", "Biology"
print(a)
print(b)
print(c)

a = b = c = "Maths"
print(a)
print(b)
print(c)

x = 5
def add():
  print(" We offer ", x , " prayers")

add()

stdData = {
    "id" : 1,
    "name" : "Fatima",
    "age" : 22
}
print(stdData)
print(stdData["id"])

stdData2 = {
    "id" : 1,
    "name" : "Fatima",
    "age" : 22,
    "age": 21
}
print(stdData2)
print(len(stdData))
stdData2.update({"age":22})
print(stdData2)

x = 2
y = 3
if x < y:
  print(x, " is the smaller value")
else:
  print(y, " is the smaller value")

a = 6
while(a > 1):
  print(a)
  a -= 1

names = ["fatima", "farwa", "maryam"]
for  x in names:
  print(x)

def greeting(name = "User"):
  print("Hello", name)

greeting("Fatima")
greeting()
greeting("Amna")

def tableFive(num):
  return 5 * num

print(tableFive(3))